# Spring Boot configuration
spring:
  #Security
  security:
    user:
      name: admin
      password: admin
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update  # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Server configuration
server:
  port: 8086 #set your port
  # Swagger configuration
  springdoc:
    swagger-ui:
      path: /swagger-ui.html # swagger-ui custom path
    api-docs:
      path: /v3/api-docs.yaml
# Logger configuration
logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: info
